### ISSUE TITLE
Add migration tooling to the cli

### ISSUE THREAD

**Issue by kesne** [fewer/fewer#29]
- `generate:schema` - This should iterate over the migrations and reduce them into a schema.
- `generate:migration` - This should scaffold out a migrationfile.
- `migrate` - This should run the migrations.
- `init` - Need to add initial schema generation.

**Comment by kesne** [comment]
We MiGhT aLsO wAnT tO aLlOw YoU To GeNeRaTe ThE sChEmA vIa A dB dUmP

**Comment by Emily** [comment]
@kesne are these done now?

**Comment by kesne** [comment]
@Emily Mostly, it's done except for `generate:schema`, which I think we should do in two ways:

`generate:schema` - Reduces all of the migrations into a single schema.
`generate:schema --online` - Connects to the DB, issues a DB dump (via a new adapter method) and builds the schema from that.

Alternatively we can flip this and do the online by default and have `--offline` to do the migration reduce method.
